### ISSUE TITLE
Napaka pri funkciji pivot_longer

### ISSUE THREAD

**Issue by MajaKomic** [MajaKomic/APPR-2021-22#1]
V datoteki uvoz.r vrstici 146 javi napako ko poženem, ki je neznam odpraviti (v vrstici 142 sem poizkusila stolpce spremeniti v numeric in tudi v character, vendar še vedno javlja enako napako), kako naj odpravim to napako?

**Comment by evadezelak** [comment]
Težava je pri uporabi funkcije pivot_longer in sicer si pozabila uporabiti colnames, ko podaš stolpce. Če to dodaš (kot si naredila zgoraj pri prvi tabeli), deluje.
