### ISSUE TITLE
Regularni izraz za tabela4.1

### ISSUE THREAD

**Issue by MajaKomic** [MajaKomic/APPR-2021-22#2]
Zanima me, kako sestaviti regularni izraz za razdelitev vrstice "vrsta.zavoda.vrsta.izobrazevanja" z regularnimi izrazi v datoteki uvoz.r, vrstice 252 do 257, poskušala sem napisati regularni izraz na podoben način, kot v tabelah 2.1 in 3.1, ampak mi cev vrne napako.

**Comment by evadezelak** [comment]
V tem stolpcu vsaka vrstica vsebuje besedo 'sredstva' ali pa 'zavodi'. Svetujem ti, da gledaš najprej, če je vsebovana beseda 'sredstva' in če je, vzameš levo od tega. Sicer pa gledaš glede na besedo 'zavodi'.
